In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('../data/train.csv')

In [2]:
context_cols = ['fuel_surcharge_pct', 'weather_severity', 'carrier_congestion_index','promised_days', 'carrier_cost_usd']

In [3]:
df[context_cols].describe()

,fuel_surcharge_pct,weather_severity,carrier_congestion_index,promised_days,carrier_cost_usd
count,40030.000000,40030.000000,40030.000000,40030.000000,40030.000000
mean,0.112494,0.260225,0.257252,5.415014,61.500261
std,0.029370,0.164361,0.252379,2.172070,105.936608
min,0.040000,0.000000,0.000000,2.000000,3.000000
25%,0.091400,0.128000,0.108000,4.000000,14.630000
50%,0.108300,0.239000,0.170000,6.000000,19.640000
75%,0.131300,0.364000,0.251000,7.000000,29.600000
max,0.220000,1.000000,1.000000,11.000000,695.000000

In [4]:
df[context_cols].isnull().sum()

fuel_surcharge_pct          0
weather_severity            0
carrier_congestion_index    0
promised_days               0
carrier_cost_usd            0
dtype: int64

In [6]:
df[df['carrier_cost_usd'] <= 0].shape

(0, 33)

In [7]:
df.groupby('ship_month')[['weather_severity', 'carrier_congestion_index']].mean()

            weather_severity  carrier_congestion_index
ship_month
1                   0.411747                  0.151742
2                   0.412871                  0.151766
3                   0.209031                  0.151061
4                   0.210106                  0.150847
5                   0.212555                  0.150125
6                   0.210937                  0.149304
7                   0.208873                  0.151669
8                   0.210710                  0.153363
9                   0.211204                  0.152169
10                  0.207417                  0.149645
11                  0.211024                  0.799604
12                  0.411209                  0.799909

In [8]:
df.groupby('shipment_mode')['carrier_cost_usd'].describe()

,count,mean,std,min,25%,50%,75%,max
shipment_mode,,,,,,,,
ltl_freight,5926.0,301.618449,88.000732,133.53,235.1925,286.27,359.57,695.00
parcel,34104.0,19.776698,8.212493,3.00,13.9600,18.04,23.82,94.98