In [102]:
import pandas as pd
import numpy as np

In [103]:

df = pd.read_csv("../data/train.csv")

In [104]:
df.head()

,shipment_id,order_date,ship_date,ship_dow,ship_month,shipment_mode,carrier,service_level,origin_metro,dest_metro,...,residential_flag,signature_required,declared_value_usd,fuel_surcharge_pct,weather_severity,carrier_congestion_index,promised_days,carrier_cost_usd,transit_days,delivered_on_time
0,SHP-42-0003885,2024-04-23,2024-04-23,1,4,parcel,Cobalt Regional,Overnight,Los Angeles CA,Salt Lake City UT,...,1,0,0.00,0.0954,0.108,0.000,2,29.53,1,1
1,SHP-42-0010239,2025-01-07,2025-01-09,3,1,parcel,Northstar Parcel,Expedited,Seattle WA,New York NY,...,1,1,178.87,0.1353,0.273,0.206,4,28.30,3,1
2,SHP-42-0035486,2025-07-30,2025-07-30,2,7,ltl_freight,Vela Freight,LTL Standard,Atlanta GA,Miami FL,...,0,0,0.00,0.0727,0.222,0.119,9,205.09,8,1
3,SHP-42-0008180,2025-03-24,2025-03-26,2,3,parcel,Northstar Parcel,Ground,New York NY,Salt Lake City UT,...,0,0,110.12,0.0917,0.046,0.287,7,11.79,6,1
4,SHP-42-0015190,2025-05-06,2025-05-08,3,5,parcel,Falcon Post,Expedited,Los Angeles CA,Columbus OH,...,0,0,14.83,0.1213,0.273,0.120,4,13.13,6,0

In [105]:
df.columns

Index(['shipment_id', 'order_date', 'ship_date', 'ship_dow', 'ship_month',
       'shipment_mode', 'carrier', 'service_level', 'origin_metro',
       'dest_metro', 'origin_zip', 'dest_zip', 'origin_lat', 'origin_lon',
       'dest_lat', 'dest_lon', 'distance_miles', 'zone', 'weight_lbs',
       'length_in', 'width_in', 'height_in', 'pallet_count',
       'residential_flag', 'signature_required', 'declared_value_usd',
       'fuel_surcharge_pct', 'weather_severity', 'carrier_congestion_index',
       'promised_days', 'carrier_cost_usd', 'transit_days',
       'delivered_on_time'],
      dtype='str')

In [106]:
df_physical_handeling = df[["weight_lbs", "length_in", "width_in", "height_in", "pallet_count", "residential_flag", "signature_required", "declared_value_usd"]]

In [107]:
df_physical_handeling.head()

,weight_lbs,length_in,width_in,height_in,pallet_count,residential_flag,signature_required,declared_value_usd
0,2.48,7.5,4.3,6.5,0,1,0,0.00
1,3.57,10.9,6.1,4.2,0,1,1,178.87
2,202.72,31.7,33.0,20.3,1,0,0,0.00
3,3.53,9.8,5.3,4.7,0,0,0,110.12
4,6.39,7.1,6.2,7.7,0,0,0,14.83

In [108]:
df_physical_handeling.describe(include='all')

,weight_lbs,length_in,width_in,height_in,pallet_count,residential_flag,signature_required,declared_value_usd
count,38863.000000,39152.000000,39199.000000,39230.000000,40030.000000,40030.000000,40030.000000,40030.000000
mean,485.567852,13.476489,11.227809,8.976605,0.159256,0.525306,0.148813,69.349724
std,11047.732743,13.532201,11.206729,9.071432,0.398533,0.499365,0.355909,103.083463
min,0.000000,4.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000
25%,2.210000,6.600000,5.600000,4.300000,0.000000,0.000000,0.000000,0.000000
50%,3.950000,8.500000,7.100000,5.700000,0.000000,1.000000,0.000000,39.175000
75%,8.260000,11.500000,9.500000,7.800000,0.000000,1.000000,0.000000,91.490000
max,935931.000000,108.000000,90.000000,70.900000,6.000000,1.000000,1.000000,2352.850000

In [109]:
df_physical_handeling.dtypes

weight_lbs            float64
length_in             float64
width_in              float64
height_in             float64
pallet_count            int64
residential_flag        int64
signature_required      int64
declared_value_usd    float64
dtype: object

In [110]:
nan_counts = np.sum(df_physical_handeling.isnull())
print("Null values: " + str(nan_counts))
df_physical_handeling.isnull().sum()

Null values: 3676

weight_lbs            1167
length_in              878
width_in               831
height_in              800
pallet_count             0
residential_flag         0
signature_required       0
declared_value_usd       0
dtype: int64

In [111]:
to_impute_ph = ["weight_lbs", "length_in", "width_in", "height_in"]
for colname in to_impute_ph:
    df[colname + '_na'] = df[colname].isnull()
for colname in to_impute_ph:
    df[colname] = df[colname].fillna(np.mean(df[colname]))
for colname in to_impute_ph:
    print('Missing values: ' + str(colname) + ': ' + str(np.sum(df.columns.isnull())) )

Missing values: weight_lbs: 0
Missing values: length_in: 0
Missing values: width_in: 0
Missing values: height_in: 0

In [112]:
##check that missing value indicating columns created
df.columns

Index(['shipment_id', 'order_date', 'ship_date', 'ship_dow', 'ship_month',
       'shipment_mode', 'carrier', 'service_level', 'origin_metro',
       'dest_metro', 'origin_zip', 'dest_zip', 'origin_lat', 'origin_lon',
       'dest_lat', 'dest_lon', 'distance_miles', 'zone', 'weight_lbs',
       'length_in', 'width_in', 'height_in', 'pallet_count',
       'residential_flag', 'signature_required', 'declared_value_usd',
       'fuel_surcharge_pct', 'weather_severity', 'carrier_congestion_index',
       'promised_days', 'carrier_cost_usd', 'transit_days',
       'delivered_on_time', 'weight_lbs_na', 'length_in_na', 'width_in_na',
       'height_in_na'],
      dtype='str')

In [113]:
df["weight_lbs"].head(15)

0       2.480000
1       3.570000
2     202.720000
3       3.530000
4       6.390000
5       2.810000
6       2.980000
7       1.150000
8       9.670000
9       3.000000
10    485.567852
11      2.730000
12      2.730000
13      2.240000
14      3.170000
Name: weight_lbs, dtype: float64

In [114]:
print((df["weight_lbs"] == 0).any())

True

In [115]:
print((df["weight_lbs"] ==0).sum())

202

In [116]:
df = df[df["weight_lbs"] !=0]

In [117]:
print((df["weight_lbs"]==0).any())

False

In [118]:
df["weight_lbs"].describe()

count     39828.000000
mean        488.030559
std       10913.014816
min           0.200000
25%           2.280000
50%           4.110000
75%           9.350000
max      935931.000000
Name: weight_lbs, dtype: float64

In [119]:
df["weight_lbs"].sort_values(ascending=False).head(1000)

917      935931.00
25672    553637.00
20618    481247.00
6056     458603.00
4067     443612.00
           ...
27594       995.05
18451       994.31
29904       993.99
7585        993.86
20107       993.22
Name: weight_lbs, Length: 1000, dtype: float64

In [120]:
suspicious = df[(df["weight_lbs"]>150) & (df["pallet_count"]==0)].copy()
suspicious["converted_weight"] = suspicious["weight_lbs"]/453.592
suspicious[["converted_weight", "weight_lbs", "length_in", "width_in", "height_in", "pallet_count"]].sort_values("weight_lbs", ascending=False).head(100)

,converted_weight,weight_lbs,length_in,width_in,height_in,pallet_count
27542,27.381435,12420.0,13.800000,14.6,9.000000,0
32750,26.250463,11907.0,11.600000,14.9,8.976605,0
27976,25.379636,11512.0,15.100000,11.9,12.400000,0
30695,21.620752,9807.0,13.476489,15.6,12.000000,0
25694,20.939523,9498.0,19.200000,12.3,13.500000,0
...,...,...,...,...,...,...
29391,5.379284,2440.0,11.400000,10.1,5.200000,0
20219,5.350623,2427.0,8.200000,8.1,5.700000,0
23490,5.319759,2413.0,7.500000,5.8,6.600000,0
4613,5.240392,2377.0,9.500000,7.9,6.400000,0
1669,5.229369,2372.0,10.200000,6.8,5.900000,0

In [122]:
condition = (df["weight_lbs"]>150) & (df["pallet_count"]==0)
df["weight_lbs"] = np.where(condition, df["weight_lbs"]/453.592, df["weight_lbs"])
df[["weight_lbs", "length_in", "width_in", "height_in", "pallet_count"]].sort_values("weight_lbs", ascending=False).head(1000)

       weight_lbs  length_in  width_in  height_in  pallet_count
917     935931.00       60.7      58.7       61.3             2
25672   553637.00       44.7      60.2       30.0             2
20618   481247.00       72.9      57.9       48.1             1
6056    458603.00       51.5      43.0       47.1             1
4067    443612.00       49.0      47.3       25.2             1
...           ...        ...       ...        ...           ...
9018       878.41       59.2      48.3       23.3             1
31494      878.15       40.1      46.9       42.3             1
24391      877.43       58.5      43.3       35.6             1
11547      876.73       50.9      42.4       32.1             1
19885      876.16       55.2      37.8       35.5             1

[1000 rows x 5 columns]